"""Print the clause parameter baseline for human review, or write it (D24).

    uv run python scripts/review_params.py            # review table
    uv run python scripts/review_params.py --write    # write the baseline YAML

`params` is what the calculators read, so a wrong value here is a wrong answer
carrying a correct-looking citation. The extraction pipeline is real, but the
committed baseline is what makes it trustworthy: it is reviewed once by a
human, and `test_clause_params_baseline.py` fails if extraction ever drifts
from it.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.knowledge.clause_parser import parse_all
from src.knowledge.params import extract_params, score_confidence

BASELINE_PATH = (
    Path(__file__).resolve().parents[1] / "src" / "knowledge" / "clause_params_baseline.yaml"
)

HEADER = """# Reviewed clause parameter baseline (D24).
#
# Generated by scripts/review_params.py, then READ BY A HUMAN before being
# committed. tests/unit/test_clause_params_baseline.py asserts that extraction
# still produces exactly this, so a re-ingest that silently changes a threshold
# fails CI instead of producing a plausible wrong answer.
#
# Do not hand-edit to make a test pass. If a value here is wrong, the extractor
# is wrong.
"""


def collect() -> dict[str, dict[str, Any]]:
    return {
        clause.clause_id: extract_params(clause)
        for document in parse_all()
        for clause in document.clauses
    }


def render(value: Any) -> str:
    if isinstance(value, dict) and {"amount", "unit"} <= set(value):
        # Rendered the way the document words it, so a reviewer is comparing
        # like with like: "1 business day", never "1 business days".
        unit = value["unit"].rstrip("s") if value["amount"] == 1 else value["unit"]
        suffix = " business" if value.get("business") else ""
        clock = ", 24x7" if value.get("always_on") else ""
        return f"{value['amount']}{suffix} {unit}{clock}".strip()
    if isinstance(value, dict):
        return "{" + ", ".join(f"{k}: {render(v)}" for k, v in value.items()) + "}"
    if isinstance(value, list):
        return "[" + ", ".join(render(v) for v in value) + "]"
    return repr(value)


def review() -> int:
    params = collect()
    flagged = 0

    for document in parse_all():
        print(f"\n{'=' * 78}")
        print(f"{document.title}   tier={document.tier}  account={document.account_id or '-'}")
        print("=" * 78)
        for clause in document.clauses:
            values = params[clause.clause_id]
            flag = score_confidence(clause.clause_id, values)
            marker = "" if flag.score == 1.0 else f"   <-- REVIEW {flag.score} {list(flag.reasons)}"
            flagged += flag.score < 1.0
            print(f"\n  {clause.clause_ref}  {clause.title}{marker}")
            if not values:
                print("      (no parameters)")
            for key, value in sorted(values.items()):
                print(f"      {key:28} {render(value)}")

    print(f"\n{'=' * 78}")
    print(f"{len(params)} clauses, {flagged} flagged for review")
    print("Check every number against the PDF, then re-run with --write.")
    return 0


def write() -> int:
    import yaml

    payload = {cid: values for cid, values in sorted(collect().items())}
    BASELINE_PATH.write_text(
        HEADER
        + yaml.safe_dump(payload, sort_keys=True, default_flow_style=False, allow_unicode=True),
        encoding="utf-8",
    )
    print(f"wrote {BASELINE_PATH} ({len(payload)} clauses)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write the baseline YAML")
    args = parser.parse_args()
    return write() if args.write else review()


if __name__ == "__main__":
    raise SystemExit(main())
