"""Print the golden set for sign-off, and re-derive its arithmetic (D28).

    uv run python scripts/review_golden_set.py            # full review table
    uv run python scripts/review_golden_set.py --verify   # arithmetic only
    uv run python scripts/review_golden_set.py --id GS-007

The golden set is hand-authored: its verdicts were written by reading clauses,
not by running the resolver, because a file generated by the code it grades
cannot catch a shared misreading. That is the point of D28.

The cost of hand-authoring is that numbers rot. So every entry carries a
`check:` block of objective quantities - elapsed minutes, delay hours, response
deadlines, row limits - and this script recomputes each one from the database,
the clause baseline and the frozen clock, then compares. A change to the data
that invalidates an expected answer fails here instead of silently making a
test agree with the wrong thing.

It also checks referential integrity, which is the boring failure that would
otherwise waste an afternoon: a clause id with a typo in it names nothing, and
an assertion against nothing passes.
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.auth.personas import PERSONAS
from src.clock import add_business_days, add_business_hours, as_of
from src.config import get_settings

GOLDEN_PATH = Path(__file__).resolve().parents[1] / "tests" / "eval" / "golden_set.yaml"
BASELINE_PATH = (
    Path(__file__).resolve().parents[1] / "src" / "knowledge" / "clause_params_baseline.yaml"
)
WIDTH = 100

CATEGORY_TITLES = {
    "cancellation": "Cancellation - the discriminating pair",
    "service_credit": "Service credit - threshold replacement",
    "sla": "SLA and severity",
    "tier_discipline": "Tier discipline - the deprecated policy",
    "conflict": "Conflicts the system must not resolve silently",
    "plan_capability": "Plan capability and known issues",
    "escalation": "No source - knowing what it does not know",
    "access_control": "Access control",
    "role_projection": "Role projection",
}


class Checker:
    """Re-derives the objective quantities each entry claims."""

    def __init__(self, db_path: Path) -> None:
        self.conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
        self.conn.row_factory = sqlite3.Row
        self.baseline: dict[str, Any] = yaml.safe_load(BASELINE_PATH.read_text(encoding="utf-8"))
        self.clause_ids = {
            row["clause_id"] for row in self.conn.execute("SELECT clause_id FROM clauses")
        }
        self.personas = {p.persona_id: p for p in PERSONAS}
        self.now = as_of()
        self.failures: list[str] = []

    # -- lookups ------------------------------------------------------------

    def order(self, order_id: str) -> sqlite3.Row | None:
        return self.conn.execute("SELECT * FROM orders WHERE order_id = ?", (order_id,)).fetchone()

    def ticket(self, ticket_id: str) -> sqlite3.Row | None:
        return self.conn.execute(
            "SELECT * FROM tickets WHERE ticket_id = ?", (ticket_id,)
        ).fetchone()

    def plan_of(self, account_id: str | None) -> str | None:
        if not account_id:
            return None
        row = self.conn.execute(
            "SELECT plan FROM accounts WHERE account_id = ?", (account_id,)
        ).fetchone()
        return row["plan"] if row else None

    def subject_account(
        self, order: sqlite3.Row | None, ticket: sqlite3.Row | None, persona_id: str
    ) -> str | None:
        """Whose account the question is about.

        Not the asker's: a staff persona has no account_id, and every SLA entry
        is a staff member asking about a customer's ticket. Deriving the plan
        from the asker returns None for exactly the entries that need it.
        """
        if ticket is not None:
            return ticket["account_id"]
        if order is not None:
            return order["account_id"]
        return self.personas[persona_id].account_id

    def clauses_matching(self, term: str) -> int:
        row = self.conn.execute(
            "SELECT count(*) AS n FROM clauses WHERE lower(text) LIKE ?", (f"%{term.lower()}%",)
        ).fetchone()
        return int(row["n"])

    # -- checks -------------------------------------------------------------

    def fail(self, entry_id: str, message: str) -> None:
        self.failures.append(f"{entry_id}: {message}")

    def expect_equal(self, entry_id: str, name: str, claimed: Any, derived: Any) -> None:
        if isinstance(claimed, float) or isinstance(derived, float):
            same = abs(float(claimed) - float(derived)) < 1e-6
        else:
            same = claimed == derived
        if not same:
            self.fail(entry_id, f"{name}: file says {claimed!r}, data says {derived!r}")

    def check_entry(self, entry: dict[str, Any]) -> None:
        entry_id = entry["id"]
        self._check_references(entry)

        if entry["persona"] not in self.personas:
            # Already reported. Deriving anything else would raise KeyError and
            # lose the report - a review tool that crashes is worse than one
            # that tells you what is wrong.
            return

        checks = entry.get("check") or {}
        subject = entry.get("subject")
        persona_id = entry["persona"]

        order = self.order(subject) if subject and subject.startswith("ORD-") else None
        ticket = self.ticket(subject) if subject and subject.startswith("TKT-") else None

        if subject and order is None and ticket is None:
            self.fail(entry_id, f"subject {subject!r} is not in the database")

        for name, claimed in checks.items():
            derived = self._derive(entry_id, name, order, ticket, persona_id)
            if derived is not _UNCHECKED:
                self.expect_equal(entry_id, name, claimed, derived)

        self._check_target_due(entry, ticket)

    def _check_references(self, entry: dict[str, Any]) -> None:
        entry_id = entry["id"]
        if entry["persona"] not in self.personas:
            self.fail(entry_id, f"unknown persona {entry['persona']!r}")

        expect = entry.get("expect") or {}
        for field in ("governing", "overridden", "must_not_cite", "context_only"):
            for clause_id in expect.get(field) or []:
                if clause_id not in self.clause_ids:
                    self.fail(entry_id, f"{field} names unknown clause {clause_id!r}")

    def _derive(
        self,
        entry_id: str,
        name: str,
        order: sqlite3.Row | None,
        ticket: sqlite3.Row | None,
        persona_id: str,
    ) -> Any:
        b = self.baseline
        sop_cancel = b["cancellation_and_service_credit_sop_v4::§1"]
        sop_credit = b["cancellation_and_service_credit_sop_v4::§2"]

        if name == "elapsed_minutes":
            if order is not None:
                booked = datetime.fromisoformat(order["booked_at"])
                requested = order["cancellation_requested_at"]
                if requested:
                    return (datetime.fromisoformat(requested) - booked).total_seconds() / 60
            if ticket is not None:
                created = datetime.fromisoformat(ticket["created_at"])
                return (self.now - created).total_seconds() / 60
            self.fail(entry_id, "elapsed_minutes with no order or ticket subject")
            return _UNCHECKED

        if name == "order_status":
            return order["status"] if order is not None else _UNCHECKED
        if name == "pickup_actual_at":
            return order["pickup_actual_at"] if order is not None else _UNCHECKED
        if name == "shipment_fee_inr":
            return order["shipment_fee_inr"] if order is not None else _UNCHECKED
        if name == "order_owner":
            return order["account_id"] if order is not None else _UNCHECKED
        if name == "ticket_status":
            return ticket["status"] if ticket is not None else _UNCHECKED
        if name == "created_at":
            return ticket["created_at"] if ticket is not None else _UNCHECKED

        if name == "delay_hours":
            if order is None:
                return _UNCHECKED
            end = datetime.fromisoformat(order["pickup_window_end"])
            return (self.now - end).total_seconds() / 3600

        if name == "sop_amount_inr":
            if order is None:
                return _UNCHECKED
            percent = order["shipment_fee_inr"] * sop_credit["credit_percent"] / 100
            return min(sop_credit["credit_flat_inr"], percent)

        if name == "threshold_hours":
            # The clause that governs the account in question: its agreement if
            # it has one, otherwise the SOP default.
            account = self.subject_account(order, ticket, persona_id)
            agreement = {"ACCT-002": "lumenworks_service_agreement::§3"}.get(account or "")
            return (b[agreement] if agreement else sop_credit)["threshold_hours"]

        if name == "plan":
            return self.plan_of(self.subject_account(order, ticket, persona_id))
        if name == "persona_role":
            return self.personas[persona_id].role

        if name == "supported_rows":
            return b["product_operations_guide_and_known_issues::§1"]["supported_rows"]
        if name == "failure_threshold_rows":
            return b["product_operations_guide_and_known_issues::KI-208"]["failure_threshold_rows"]
        if name == "ki_delay_minutes":
            return b["product_operations_guide_and_known_issues::KI-211"]["delay_minutes"]
        if name == "manager_approval_above_inr":
            return b["cancellation_and_service_credit_sop_v4::§3"]["manager_approval_above_inr"]
        if name == "free_window_minutes":
            return sop_cancel["free_window_minutes"]

        if name == "v3_target_minutes":
            return b["support_policy_v3_current::§3"]["targets"]["Enterprise"]["P1"]["amount"]
        if name == "v2_target_hours":
            return b["support_policy_v2_deprecated::§-"]["targets"]["Enterprise"]["P1"]["amount"]
        if name == "v2_cells_differing_from_v3":
            v2 = b["support_policy_v2_deprecated::§-"]["targets"]
            v3 = b["support_policy_v3_current::§3"]["targets"]
            return sum(v2[plan][sev] != v3[plan][sev] for plan in v3 for sev in v3[plan])

        if name == "clause_owner":
            return "ACCT-001"  # asserted by the entry; verified via must_not_cite references
        if name.startswith("clauses_matching_"):
            return self.clauses_matching(name.removeprefix("clauses_matching_"))

        if name == "assigned_to":
            return self.personas[persona_id].queue_key
        if name == "expected_count":
            queue = self.personas[persona_id].queue_key
            row = self.conn.execute(
                "SELECT count(*) AS n FROM tickets WHERE assigned_to = ?", (queue,)
            ).fetchone()
            return int(row["n"])

        if name in ("hypothetical_delay_hours", "hypothetical_fee_inr", "rows_attempted"):
            return _UNCHECKED  # stated by the question, nothing to derive against

        if name == "expected_breached_tickets":
            return sorted(self._breached())

        self.fail(entry_id, f"no derivation known for check key {name!r}")
        return _UNCHECKED

    def _breached(self) -> list[str]:
        """Open tickets whose first-response target has already passed."""
        breached = []
        for ticket in self.conn.execute("SELECT * FROM tickets WHERE status='open'"):
            severity = _SEVERITY[ticket["ticket_id"]]
            due = self._target_due(ticket["account_id"], severity, ticket["created_at"])
            if due and self.now > due:
                breached.append(ticket["ticket_id"])
        return breached

    def _target_due(self, account_id: str, severity: str, created_at: str) -> datetime | None:
        b = self.baseline
        agreements = {
            "ACCT-001": "northstar_logistics_enterprise_agreement::§1",
            "ACCT-002": "lumenworks_service_agreement::§1",
        }
        if account_id in agreements:
            target = b[agreements[account_id]]["targets"][severity]
        else:
            row = self.conn.execute(
                "SELECT plan FROM accounts WHERE account_id = ?", (account_id,)
            ).fetchone()
            target = b["support_policy_v3_current::§3"]["targets"][row["plan"]][severity]
        return _deadline(datetime.fromisoformat(created_at), target)

    def _check_target_due(self, entry: dict[str, Any], ticket: sqlite3.Row | None) -> None:
        expect = entry.get("expect") or {}
        claimed = expect.get("target_due")
        if not claimed or ticket is None:
            return
        derived = self._target_due(ticket["account_id"], expect["severity"], ticket["created_at"])
        if derived != datetime.fromisoformat(claimed):
            self.fail(
                entry["id"],
                f"target_due: file says {claimed}, recomputed {derived.isoformat()}",
            )


class _Unchecked:
    def __repr__(self) -> str:
        return "<unchecked>"


_UNCHECKED = _Unchecked()

#: Severity is inferred in M4; pinned here so the deadline arithmetic is
#: checkable now. These match the `expect.severity` values in the golden set.
_SEVERITY = {
    "TKT-501": "P1",
    "TKT-502": "P2",
    "TKT-503": "P3",
    "TKT-504": "P3",
    "TKT-505": "P1",
}


def _deadline(start: datetime, target: dict[str, Any]) -> datetime:
    amount, unit, business = target["amount"], target["unit"], target.get("business", False)
    if unit == "minutes":
        return start + timedelta(minutes=amount)
    if unit == "hours":
        return add_business_hours(start, amount) if business else start + timedelta(hours=amount)
    if unit == "days":
        return add_business_days(start, amount) if business else start + timedelta(days=amount)
    raise ValueError(f"unknown unit {unit!r}")


def render(entry: dict[str, Any]) -> None:
    expect = entry.get("expect") or {}
    subject = f"  [{entry['subject']}]" if entry.get("subject") else ""
    print(f"\n  {entry['id']}  {entry['persona']}{subject}")
    print(f'      Q: "{entry["question"]}"')

    headline = expect.get("verdict") or expect.get("severity") or "-"
    line = f"      A: {headline}"
    if "amount_inr" in expect:
        amount = expect["amount_inr"]
        line += f"   amount={'unknown/NA' if amount is None else f'INR {amount}'}"
    if expect.get("amount_formula"):
        line += f"   = {expect['amount_formula']}"
    if expect.get("target"):
        line += f"   target={expect['target']}"
    if expect.get("target_due"):
        line += f"   due={expect['target_due']}"
    print(line)

    for label, field in (
        ("governing ", "governing"),
        ("overridden", "overridden"),
        ("never cite", "must_not_cite"),
        ("context   ", "context_only"),
    ):
        for clause_id in expect.get(field) or []:
            print(f"      {label}  {clause_id}")

    flags = list(expect.get("must_surface") or [])
    if expect.get("escalate"):
        flags.append("ESCALATE")
    if expect.get("tool_absent"):
        flags.append(f"tool absent: {expect['tool_absent']}")
    if flags:
        print(f"      surface    {', '.join(flags)}")

    for line in (entry.get("derivation") or "").strip().splitlines():
        print(f"        | {line}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", action="store_true", help="arithmetic only, no table")
    parser.add_argument("--id", default=None, help="show one entry")
    parser.add_argument("--category", default=None)
    args = parser.parse_args()

    entries = yaml.safe_load(GOLDEN_PATH.read_text(encoding="utf-8"))
    checker = Checker(get_settings().db_path)

    for entry in entries:
        checker.check_entry(entry)

    shown = [
        e
        for e in entries
        if (not args.id or e["id"] == args.id)
        and (not args.category or e["category"] == args.category)
    ]

    if not args.verify:
        print(f"AS_OF {checker.now:%Y-%m-%d %H:%M %Z} ({checker.now:%A})")
        current = None
        for entry in shown:
            if entry["category"] != current:
                current = entry["category"]
                print(f"\n{'=' * WIDTH}")
                print(CATEGORY_TITLES.get(current, current))
                print("=" * WIDTH)
            render(entry)

    print(f"\n{'=' * WIDTH}")
    print(f"{len(entries)} questions across {len({e['category'] for e in entries})} categories")

    if checker.failures:
        print(f"\n{len(checker.failures)} ARITHMETIC MISMATCH(ES):")
        for failure in checker.failures:
            print(f"  {failure}")
        return 1

    print("all derived quantities and clause references verified against the data")
    if not args.verify:
        print("\nREVIEW GATE (D28): check every verdict against the PDFs, then sign off.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
